[colors.bright]
black = "#8f9aae"
blue = "#10b1fe"
cyan = "#5fb9bc"
green = "#3fc56b"
magenta = "#ff78f8"
red = "#ff6480"
white = "#ffffff"
yellow = "#f9c859"

[colors.cursor]
cursor = "#ffcc00"
text = "#282c34"

[colors.normal]
black = "#41444d"
blue = "#3476ff"
cyan = "#4483aa"
green = "#25a45c"
magenta = "#7a82da"
red = "#fc2f52"
white = "#cdd4e0"
yellow = "#ff936a"

[colors.primary]
background = "#282c34"
foreground = "#b9c0cb"

[colors.selection]
background = "#b9c0ca"
text = "#272b33"

[schemes.bluloco_dark.bright]
black = "#8f9aae"
blue = "#10b1fe"
cyan = "#5fb9bc"
green = "#3fc56b"
magenta = "#ff78f8"
red = "#ff6480"
white = "#ffffff"
yellow = "#f9c859"

[schemes.bluloco_dark.cursor]
cursor = "#ffcc00"
text = "#282c34"

[schemes.bluloco_dark.normal]
black = "#41444d"
blue = "#3476ff"
cyan = "#4483aa"
green = "#25a45c"
magenta = "#7a82da"
red = "#fc2f52"
white = "#cdd4e0"
yellow = "#ff936a"

[schemes.bluloco_dark.primary]
background = "#282c34"
foreground = "#b9c0cb"

[schemes.bluloco_dark.selection]
background = "#b9c0ca"
text = "#272b33"

[schemes.bluloco_light.bright]
black = "#676a77"
blue = "#0099e1"
cyan = "#6d93bb"
green = "#3cbc66"
magenta = "#ce33c0"
red = "#ff6480"
white = "#d3d3d3"
yellow = "#c5a332"

[schemes.bluloco_light.cursor]
cursor = "#f32759"
text = "#ffffff"

[schemes.bluloco_light.normal]
black = "#373a41"
blue = "#275fe4"
cyan = "#27618d"
green = "#23974a"
magenta = "#823ff1"
red = "#d52753"
white = "#babbc2"
yellow = "#df631c"

[schemes.bluloco_light.primary]
background = "#f9f9f9"
foreground = "#373a41"

[schemes.bluloco_light.selection]
background = "#daf0ff"
text = "#373a41"
